## Creating a Tensor from python List

In [1]:
import torch

In [2]:
data = 32
my_tensor = torch.tensor(data)
print(my_tensor)

tensor(32)


In [3]:
my_tensor.shape

torch.Size([])

In [6]:

#Input: A standard python list
data = [[1,2,3], [4,5,6]]
my_tensor = torch.tensor(data)

print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
my_tensor.shape

torch.Size([2, 3])

In [8]:
my_tensor.ndim

2

In [ ]:
len(my_tensor.shape)

2

### **You Know the shape, but not the values yet.**

In [10]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.7804,  0.8362, -0.5716],
        [-0.1628,  0.6950, -1.0127]])


In [11]:
tensor = torch.randn(3,4)
print(f"Shape: {tensor.shape}")
print(f"Datatype: {tensor.dtype}")
print(f"Device: {tensor.device}")

Shape: torch.Size([3, 4])
Datatype: torch.float32
Device: cpu


In [12]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20], [30, 40]])

# Calculation: [[1*10, 2*20], [3*30, 4*40]]
element_wise_product = a * b

print(f"Tensor a:\n {a}\n")
print(f"Tensor b:\n {b}\n")
print(f"Element-wise Product (a * b):\n {element_wise_product}")

Tensor a:
 tensor([[1, 2],
        [3, 4]])

Tensor b:
 tensor([[10, 20],
        [30, 40]])

Element-wise Product (a * b):
 tensor([[ 10,  40],
        [ 90, 160]])


In [13]:
m1 = torch.tensor([[1, 2, 3], [4, 5, 6]])   # Shape: (2, 3)
m2 = torch.tensor([[7, 8], [9, 10], [11, 12]]) # Shape: (3, 2)

# Calculation for the first element: (1*7) + (2*9) + (3*11) = 58
matrix_product = m1 @ m2 # Resulting shape: (2, 2)

print(f"Matrix 1 (shape {m1.shape}):\n {m1}\n")
print(f"Matrix 2 (shape {m2.shape}):\n {m2}\n")
print(f"Matrix Product (m1 @ m2):\n {matrix_product}")

Matrix 1 (shape torch.Size([2, 3])):
 tensor([[1, 2, 3],
        [4, 5, 6]])

Matrix 2 (shape torch.Size([3, 2])):
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

Matrix Product (m1 @ m2):
 tensor([[ 58,  64],
        [139, 154]])


## Changing the SHAPE

In [14]:
m1 = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])   # Shape: (3, 5)
m1.shape

torch.Size([3, 5])

In [18]:
m1.view(5,-1)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [22]:
shape = (3,4)
m = torch.randn(shape)
m.shape

torch.Size([3, 4])

In [23]:
shape = (6,2)
n = torch.randn(shape)

In [25]:
m @ n.view(4, -1)

tensor([[-2.3566, -1.0423, -1.3545],
        [ 1.5091, -1.6738,  0.6254],
        [ 4.0840, -2.1255,  1.5347]])