In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/sabah0312/ml-datasets/refs/heads/main/regression_toy_data'
df = pd.read_csv(url,   delim_whitespace=True)

df

/tmp/ipython-input-4054934967.py:3: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(url,   delim_whitespace=True)


X       y
0 -0.5868 -0.0629
1  2.3774  5.5750
2 -1.2226 -1.2777
3  1.7578  4.6421
4 -0.8263 -0.6274
5  0.0053  1.2752
6 -1.0513 -1.1674
7 -1.4091 -1.6157
8  0.8233  2.6576
9  0.6964  2.3758

In [2]:
import torch

X = torch.tensor(df['X'].values, dtype= torch.float32)
y = torch.tensor(df['y'].values, dtype= torch.float32)
X = X.reshape(-1,1)
y = y.reshape(-1,1)

In [3]:
class Perceptron:
  def __init__(self, num_features, learning_rate = 0.01):
    self.linear = torch.nn.Linear(num_features, 1)
    self.learning_rate = learning_rate
    self.optimizer = torch.optim.SGD(self.linear.parameters(), lr = learning_rate)
    self.loss_fn = torch.nn.MSELoss()

  def forward(self, x):
    return  self.linear(x)

  def update(self, x, y_true):
    predictions = self.forward(x)
    loss = self.loss_fn(predictions, y_true)
    loss.backward()
    self.optimizer.step()
    self.optimizer.zero_grad()
    return loss

In [4]:
PPn = Perceptron(1)

print(f"initial weights: {PPn.linear.weight}")
print(f"initial bias : {PPn.linear.bias}")
epoch_no = 150
for epoch in range(epoch_no):
  loss = PPn.update(X, y)
  if epoch%10 == 0:
    print(f"epoch: {epoch}/ {epoch_no}, loss: {loss}")
print(f" weights: {PPn.linear.weight}")
print(f" bias : {PPn.linear.bias}")

initial weights: Parameter containing:
tensor([[-0.3210]], requires_grad=True)
initial bias : Parameter containing:
tensor([-0.7535], requires_grad=True)
epoch: 0/ 150, loss: 11.808725357055664
epoch: 10/ 150, loss: 6.621091365814209
epoch: 20/ 150, loss: 3.752340316772461
epoch: 30/ 150, loss: 2.1527059078216553
epoch: 40/ 150, loss: 1.252241849899292
epoch: 50/ 150, loss: 0.7399387359619141
epoch: 60/ 150, loss: 0.4450540542602539
epoch: 70/ 150, loss: 0.27318158745765686
epoch: 80/ 150, loss: 0.17168813943862915
epoch: 90/ 150, loss: 0.11095088720321655
epoch: 100/ 150, loss: 0.07411981374025345
epoch: 110/ 150, loss: 0.05149833485484123
epoch: 120/ 150, loss: 0.03743591904640198
epoch: 130/ 150, loss: 0.02859676443040371
epoch: 140/ 150, loss: 0.022985173389315605
 weights: Parameter containing:
tensor([[1.9382]], requires_grad=True)
 bias : Parameter containing:
tensor([0.9878], requires_grad=True)


In [5]:
class LR(torch.nn.Module):
  def __init__(self, num_features, learning_rate = 0.01):
    super().__init__()
    self.linear = torch.nn.Linear(num_features, 1)
    self.learning_rate = learning_rate
    self.optimizer = torch.optim.SGD(self.linear.parameters(), lr = learning_rate)
    self.loss_fn = torch.nn.MSELoss()

  def forward(self, x):
    return  self.linear(x)

  def update(self, x, y_true):
    predictions = self.forward(x)

    loss = self.loss_fn(predictions, y_true)

    loss.backward()
    self.optimizer.step()
    self.optimizer.zero_grad()

    return loss

In [ ]:
PPn = Perceptron(1)

print(f"initial weights: {PPn.linear.weight}")
print(f"initial bias : {PPn.linear.bias}")
epoch_no = 150
for epoch in range(epoch_no):
  loss = PPn.update(X, y)
  if epoch%10 == 0:
    print(f"epoch: {epoch}/ {epoch_no}, loss: {loss}")
print(f" weights: {PPn.linear.weight}")
print(f" bias : {PPn.linear.bias}")

initial weights: Parameter containing:
tensor([[0.5284]], requires_grad=True)
initial bias : Parameter containing:
tensor([0.4674], requires_grad=True)
epoch: 0/ 150, loss: 3.6116671562194824
epoch: 10/ 150, loss: 1.9521989822387695
epoch: 20/ 150, loss: 1.0615789890289307
epoch: 30/ 150, loss: 0.582353949546814
epoch: 40/ 150, loss: 0.32367226481437683
epoch: 50/ 150, loss: 0.18349672853946686
epoch: 60/ 150, loss: 0.10718120634555817
epoch: 70/ 150, loss: 0.06539903581142426
epoch: 80/ 150, loss: 0.04237106442451477
epoch: 90/ 150, loss: 0.029580259695649147
epoch: 100/ 150, loss: 0.0224117673933506
epoch: 110/ 150, loss: 0.018353354185819626
epoch: 120/ 150, loss: 0.01602981425821781
epoch: 130/ 150, loss: 0.014683296903967857
epoch: 140/ 150, loss: 0.01389284897595644
 weights: Parameter containing:
tensor([[1.9410]], requires_grad=True)
 bias : Parameter containing:
tensor([1.0439], requires_grad=True)


## Linear Classifier with Gradient